// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  apresentation: dynamic(() => import('./Apresentation')),
  hero: dynamic(() => import('./Hero')),
  ras: dynamic(() => import('./Ras')),
  text: dynamic(() => import('./Text')),
};
